### ISSUE TITLE
Force full hostname

### ISSUE THREAD

**Issue by Koma-Andrea** [agnoster/agnoster-zsh-theme#37] opened 2017-05-10 08:46 UTC
Hi,
I'm using agnoster on many machnes and many users on that machines.
When logging and using su/sudo su i cannot deistingish different machines with same username pecause i loose the "SSH_CLIENT" on the su.

There is a way to force the hostname to be always displayed?

**Comment by koma85** [comment] 2017-05-10 08:58
My bad the problem is related to powerline, forcing an unexistent DEFAULT_USER solved the situation

**Comment by apjanke** [comment] 2020-01-02 23:58
Closing per user's report.

**Closed by apjanke** 2020-01-02 23:58 UTC
