### ISSUE TITLE
terminal display [?] 

### ISSUE THREAD

**Issue by zymr-keshav** [agnoster/agnoster-zsh-theme#69] opened 2018-03-26 17:47 UTC
macOS v 10.13.3 ( High Sierra)
terminal v 2.8 (400)

I have changed theme to agnoster but when I see the terminal, it display the question mark in bracket [?]

<img width="857" alt="zymr screen shot 2018-03-26 at 11 14 41 pm" src="https://user-images.githubusercontent.com/20237647/37922933-8e8bef4e-314b-11e8-90d3-ad9d189ebf7c.png">

what is wrong?

**Comment by griiid** [comment] 2018-03-27 13:52
try answer of this issue?

https://github.com/agnoster/agnoster-zsh-theme/issues/25

**Comment by zymr-keshav** [comment] 2018-03-27 17:16
<img width="312" alt="zymr screen shot 2018-03-27 at 10 40 02 pm" src="https://user-images.githubusercontent.com/20237647/37983047-dfad36fc-320f-11e8-9948-203044aee131.png">

yes I have Installed the fonts and able to see the powerline icon but it looks very ugly ( padding is much larger and powerline icon is also not aligned)  maybe I have chosen something wrong.. here see the list of fonts comes in my terminal

There are no **Menlo for Powerline** but many other fonts

**Comment by griiid** [comment] 2018-03-28 13:26
I tried Menlo for Powerline, it really looks ugly lol

The font I use is **Droid Sans Mono for Powerline**  
If u don't have it, you can install them from this git:  
https://github.com/powerline/fonts

**Comment by zymr-keshav** [comment] 2018-03-29 12:24
I have installed that's why getting this list with powerline

**Comment by griiid** [comment] 2018-03-29 14:49
I knew it, but maybe you can try another font for powerline, such as **Droid Sans Mono for Powerline**?

Also, if you can take a picture of ur terminal, other people can understand ur situation more :)

**Comment by joni-f-g** [comment] 2018-04-16 21:31
Make sure when you're changing your font that you are on the proper profile, i.e. the profile with the text 'Default' beneath it in the sidebar. I had this issue and simply was changing the font for an inactive profile.

**Comment by fenixadar** [comment] 2019-03-04 07:25
after u install Powerline, u must set font with XXX for Powerline manual

**Comment by apjanke** [comment] 2020-01-02 23:27
Dupe of #25 – needs Powerline-patched fonts.

**Closed as completed by apjanke** 2020-01-02 23:27 UTC
