### ISSUE TITLE
ssh from ubuntu to mac shows messy code

### ISSUE THREAD

**Issue by videni** [agnoster/agnoster-zsh-theme#56] opened 2017-10-11 01:48 UTC
this theme works well in each system ,  but when I ssh from ubuntu to  mac , it shows  some messy code, 

![image](https://user-images.githubusercontent.com/4058341/31418528-06cf1618-ae69-11e7-85d8-57c859583fab.png)

**Comment by RiderExMachina** [comment] 2017-10-11 02:28
Does Ubuntu have the Patched Fonts installed?

**Comment by videni** [comment] 2017-10-11 02:40
@RiderExMachina , yep , I clone that repo , install those fonts as the instruction.  echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"   in terminal , the result is correct

**Comment by RiderExMachina** [comment] 2017-10-11 02:47
I know I'm almost to the point of beating a dead horse, but I have to be thorough: in Ubuntu you're using one of the patched fonts in your terminal?

**Comment by videni** [comment] 2017-10-11 03:07
I think I used them all , I can see all fonts in `~/.local/share/fonts`  dir

**Comment by RiderExMachina** [comment] 2017-10-11 03:08
Huh, okay. That's really strange.

**Comment by videni** [comment] 2017-10-11 09:41
seems , it is the escape character does't display well,  see this link https://superuser.com/questions/33914/why-doesnt-echo-support-e-escape-when-using-the-e-argument-in-macosx

**Comment by andrelramos** [comment] 2017-10-13 14:08
+1

**Comment by apjanke** [comment] 2020-01-02 23:44
@RiderExMachina - You can tell he's using a Powerline-patched font in his local terminal emulator because the triangle for the segment separator is displaying properly. That's a private-use-area character that's only defined in Powerline fonts.

This bug is two years old. Are people still seeing this issue? If so, what versions of Ubuntu and macOS are you getting them on?

@videni - I don't think that's what's going on. If that were it, you'd see literal backslashes in the output, not the Unicode tofu in the screen shot (square boxes with itty bitty characters in them).

I think the problem is this: https://www.reddit.com/r/emacs/comments/5p3njk/help_terminal_zsh_control_characters_in_prompt/. That is:
* The terminal you're using on Mac supports the new/proprietary \e1337;A / \e1337;B escape sequences for "start prompt" / "end prompt"
* The terminal you're using on Linux doesn't support those
* But when you ssh from your Linux terminal to your Mac box, the shell runs there, and it assumes since you're on a Mac that your terminal does support those start prompt/end prompt escape sequences. But your terminal doesn't, so it just displays them as the literal characters they contain.

I suspect this is not an Agnoster problem as such: AFAIK, Agnoster does not introduce the start/end prompt escapes. I suspect this is something else in the zsh configuration on your Mac, maybe in your `/etc/zshrc*` files. Or maybe in Oh My Zsh, if you're using that. Can you tell us a bit more about your zsh configuration on the Mac side?

**Comment by apjanke** [comment] 2020-01-03 01:33
I believe this has actually been fixed in macOS's `/etc` files as of macOS 10.14 Mojave, or maybe earlier. If this is still a problem, please re-open and let us know which version of macOS you're using on the Mac your ssh-ing in to.

**Closed as completed by apjanke** 2020-01-03 01:33 UTC
Labels: user-configuration
