### ISSUE TITLE
Line height issue in PHPStorm

### ISSUE THREAD

**Issue by SturmB** [agnoster/agnoster-zsh-theme#79] opened 2018-06-11 15:37 UTC
I'm running PHPStorm 2018.1, which has a built-in terminal, and am seeing this odd line-height that is reported on in other apps. It's obviously not a major bug (it's not a show-stopper by any means), but it does trigger my OCD alarms:
<img width="420" alt="screen shot 2018-06-11 at 11 33 51 am" src="https://user-images.githubusercontent.com/6216224/41241608-5f1678a4-6d6b-11e8-8b0f-cac343716f6c.png">
I've tried altering `Preferences`->`Editor`->`Color Scheme`->`Console Font`->`Size` and ...->`Line Spacing`, with no luck.
<img width="679" alt="screen shot 2018-06-11 at 11 36 26 am" src="https://user-images.githubusercontent.com/6216224/41241725-bb2831c8-6d6b-11e8-8cc1-eb7425e6e4db.png">
Any thoughts?

**Comment by Rems19** [comment] 2018-08-10 00:09
I'm having the exact same issue and it's triggering me. I hope a fix will eventually come.

**Comment by guitorioadar** [comment] 2019-10-15 04:55
It's been a while since the issue is open... please solve this issue... thanks again in advance...

**Comment by apjanke** [comment] 2020-01-02 23:03
This might not be something that Agnoster can fix, because this looks like an interaction of the glyphs in the Powerline font you're using with your terminal's text rendering & line height configuration.

That segment-separator arrow is a regular old font glyph that looks like a right-pointing triangle, and it uses a background/foreground color swapping trick to make it look like the first segment is pointing into the second segment. That glyph is of a fixed size, I think; there's no "expand to maximum line height" option for it.

What happens if you use the "LG M" or "LG L" variants of the Meslo LG font? Those affect line spacing. (Probably won't work, but worth a try.)

When you say you altered the line spacing, did you try making it smaller? How small?

**Comment by SturmB** [comment] 2020-01-03 19:49
Correct, @apjanke, line spacing doesn't appear to be the issue here. Trying all of the Meslo fonts did not help.

Also, after having tried out a few other different terminal programs (iTerm2 on Mac, Cmder, ConEmu, mintty, wsltty, etc.), I can confidently say that this problem is specific to PHPStorm or, more likely, all of JetBrains' IDEs. I do not think it is something that Agnoster can fix.

That said, this problem still confuses me and is annoying. Unfortunately, however, it appears to be at the bottom of JetBrains' to-do list.

**Comment by apjanke** [comment] 2020-01-03 20:01
I agree that this seems to be an issue with PHPStorm's terminal. Closing as "not something Agnoster can fix". Sorry.

**Closed as completed by apjanke** 2020-01-03 20:01 UTC
Labels: terminal-cosmetics

**Comment by jinseobhong** [comment] 2021-06-01 00:51
Still having the same problem gnome-shell.
